# Generated by Django 4.2.5 on 2023-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Neobis Project 3', max_length=255),
        ),
    ]
