# Generated by Django 4.2.5 on 2023-11-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
